### ISSUE TITLE
Plugin registration error

### ISSUE THREAD

**Issue by AttilaVM** [venomgfx/amaranth#10]
When I try to enable the add-on I get the following traceback:

```
Traceback (most recent call last):
  File "/home/attila/programs/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/home/attila/.config/blender/2.78/scripts/addons/amaranth/__init__.py", line 118, in register
    _call_globals("register")
  File "/home/attila/.config/blender/2.78/scripts/addons/amaranth/__init__.py", line 107, in _call_globals
    getattr(m, attr_name)()
  File "/home/attila/.config/blender/2.78/scripts/addons/amaranth/misc/color_management.py", line 76, in register
    bpy.utils.register_class(AMTH_AddPresetColorManagement)
ValueError: register_class(...): already registered as a subclass
```

And when I open up the preferences window I get the following traceback in the terminal as Blender's stderror:

```
  File "/home/attila/programs/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/modules/bpy_types.py", line 673, in draw_ls
    func(self, context)
  File "/home/attila/.config/blender/2.78/scripts/addons/amaranth/render/remember_layers.py", line 211, in ui_layers_for_render_header
    preferences = context.user_preferences.addons["amaranth"].preferences
KeyError: 'bpy_prop_collection[key]: key "amaranth" not found'
```

I use Gentoo Linux with vanilla Blender 2.78 downloaded from blender.org, amaranth was installed as described in the README.md.

**Comment by L0Lock** [comment]
I have the same problem on Windows 10 Blender 2.79 :

```
Modules Installed (amaranth) from 'C:\\Users\\loicd\\Downloads\\scene_amaranth_toolset.zip' into 'C:\\Users\\loicd\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\loicd\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\amaranth\__init__.py", line 118, in register
    _call_globals("register")
  File "C:\Users\loicd\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\amaranth\__init__.py", line 107, in _call_globals
    getattr(m, attr_name)()
  File "C:\Users\loicd\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\amaranth\prefs.py", line 129, in register
    bpy.utils.register_class(AmaranthToolsetPreferences)
ValueError: register_class(...): already registered as a subclass
```

**Comment by L0Lock** [comment]
Solved by unpacking a fresh downloaded blender over my blender installation. After that I could activate the addon without any trouble.

**Comment by venomgfx** [comment]
Blender, when downloaded from builder.blender.org (or when built from the sources) will come packed with Amaranth in the 'testing' section of the add-ons. The latest version at the moment of this writing being 1.0.5, many fixes have been done since then including this one.
